name: Test Hibernation Astro
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

    steps:
      # Step 1: Checkout the repository with full commit history.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install the Astro CLI.
      - name: Install Astro CLI
        run: |
          if [[ "$CLI_VERSION" == "" ]]; then
            curl -sSL https://install.astronomer.io | sudo bash -s
          else
            curl -sSL https://install.astronomer.io | sudo bash -s -- $CLI_VERSION
          fi

      # Step 3: Hibernating.
      - name: Hibernating
        shell: bash
        run: |
          echo "hibernating..."
          astro workspace switch clluiel1k003e01mvnrb8yw54
          astro deployment hibernate --deployment-name target --for "14h"  --force
