name: Astronomer CI - Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create image tag
        id: image_tag
        run: echo "image_tag=astro-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ steps.image_tag.outputs.image_tag }}
          build-args: |
            ENV=prod
            AIRFLOW_ENV=production

      - name: Deploy to Astronomer
        uses: astronomer/deploy-action@v0.11.0
        with:
          deployment-id: cmggb42tp1ngt01q6q2paftn1
          image-name: ${{ steps.image_tag.outputs.image_tag }}
          deploy-type: image-and-dags
